/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotelreservationsystem;

import java.awt.event.ActionEvent;
import java.sql.SQLException;

/**
 *
 * @author Emmanuel
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        employeeIDField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        validateCredentialsBTN = new javax.swing.JButton();
        mainCustomerPanel = new javax.swing.JPanel();
        existingCustomerBTN = new javax.swing.JButton();
        newCustomerBTN = new javax.swing.JButton();
        searchCustomerPanel = new javax.swing.JPanel();
        searchNameBTN = new javax.swing.JButton();
        searchPhoneBTN = new javax.swing.JButton();
        searchEmailBTN = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        searchCustomerLastNameField = new javax.swing.JTextField();
        searchCustomerFirstNameField = new javax.swing.JTextField();
        phonePanel = new javax.swing.JPanel();
        searchCustomerPhoneField = new javax.swing.JFormattedTextField();
        emailPanel = new javax.swing.JPanel();
        searchCustomerEmailField = new javax.swing.JTextField();
        NewCustomerPanel = new javax.swing.JPanel();
        ncPhoneField = new javax.swing.JFormattedTextField();
        ncFirstNameField = new javax.swing.JTextField();
        ncLastNameField = new javax.swing.JTextField();
        ncCityField = new javax.swing.JTextField();
        ncBirthField = new javax.swing.JFormattedTextField();
        ncStreetField = new javax.swing.JTextField();
        ncEmailField = new javax.swing.JTextField();
        ncCountryField = new javax.swing.JTextField();
        ncStateField = new javax.swing.JTextField();
        ncTitleLabel = new javax.swing.JLabel();
        ncClearButton = new javax.swing.JButton();
        ncSubmitBTN = new javax.swing.JButton();
        mainReservationPanel = new javax.swing.JPanel();
        mrNewReservationBTN = new javax.swing.JButton();
        mrExistingReservationBTN = new javax.swing.JButton();
        newReservationPanel = new javax.swing.JPanel();
        nrCheckOutField = new javax.swing.JFormattedTextField();
        nrTitleLabel = new javax.swing.JLabel();
        ncClearButton2 = new javax.swing.JButton();
        ncSubmitBTN2 = new javax.swing.JButton();
        nrRoomsField = new javax.swing.JTextField();
        nrCheckInField = new javax.swing.JFormattedTextField();
        roomTypeComboBox = new javax.swing.JComboBox<>();
        nrGuestField = new javax.swing.JTextField();
        existingReservationPanel = new javax.swing.JPanel();
        ecSearchByNumberPanel = new javax.swing.JPanel();
        erNumberField = new javax.swing.JTextField();
        erTitleLabel = new javax.swing.JLabel();
        ecSearchByNamePanel = new javax.swing.JPanel();
        erFirstNameField = new javax.swing.JTextField();
        erLastNameField = new javax.swing.JTextField();
        erCheckInField = new javax.swing.JFormattedTextField();
        ecSearchNameBTN = new javax.swing.JButton();
        ecSearchNumberBTN = new javax.swing.JButton();
        customerDisplayPanel = new javax.swing.JPanel();
        cdPhoneField = new javax.swing.JFormattedTextField();
        cdFirstNameField = new javax.swing.JTextField();
        cdLastNameField = new javax.swing.JTextField();
        cdCityField = new javax.swing.JTextField();
        cdBirthField = new javax.swing.JFormattedTextField();
        cdStreetField = new javax.swing.JTextField();
        cdEmailField = new javax.swing.JTextField();
        cdCountryField = new javax.swing.JTextField();
        cdStateField = new javax.swing.JTextField();
        cdTitleLabel = new javax.swing.JLabel();
        cdClearBTN = new javax.swing.JButton();
        cdSubmitBTN = new javax.swing.JButton();
        modifyReservationPanel = new javax.swing.JPanel();
        mrCheckOutField = new javax.swing.JTextField();
        mrReservationNumberField = new javax.swing.JTextField();
        mrLNameField = new javax.swing.JTextField();
        mrFNameField = new javax.swing.JTextField();
        mrCheckInField = new javax.swing.JTextField();
        mrPhoneField = new javax.swing.JTextField();
        mrRoomTypeField = new javax.swing.JTextField();
        mrRoomNumbersField = new javax.swing.JTextField();
        mrGuestsField = new javax.swing.JTextField();
        mrCostField = new javax.swing.JTextField();
        mrDeleteBTN = new javax.swing.JButton();
        mrModifyBTN = new javax.swing.JButton();
        finalizeReservationPanel = new javax.swing.JPanel();
        frCheckOutField = new javax.swing.JTextField();
        frResNumField = new javax.swing.JTextField();
        frLastNameField = new javax.swing.JTextField();
        frFirstNameField = new javax.swing.JTextField();
        frCheckInField = new javax.swing.JTextField();
        frPhoneField = new javax.swing.JTextField();
        frRoomTypeField = new javax.swing.JTextField();
        frRoomNumbersField = new javax.swing.JTextField();
        frGuestsField = new javax.swing.JTextField();
        frCostField = new javax.swing.JTextField();
        frCancelBTN = new javax.swing.JButton();
        frFinalizeBTN = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        returnCustomerBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Manager Program");

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(new java.awt.CardLayout());

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginLabel.setToolTipText("");

        employeeIDField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        validateCredentialsBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validateCredentialsBTN.setText("Validate Credentials");
        validateCredentialsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateCredentialsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(validateCredentialsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(employeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(validateCredentialsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "card11");

        existingCustomerBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        existingCustomerBTN.setText("Existing Customer");
        existingCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingCustomerBTNActionPerformed(evt);
            }
        });

        newCustomerBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newCustomerBTN.setText("New Customer");
        newCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainCustomerPanelLayout = new javax.swing.GroupLayout(mainCustomerPanel);
        mainCustomerPanel.setLayout(mainCustomerPanelLayout);
        mainCustomerPanelLayout.setHorizontalGroup(
            mainCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCustomerPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(newCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(existingCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        mainCustomerPanelLayout.setVerticalGroup(
            mainCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCustomerPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(mainCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        mainPanel.add(mainCustomerPanel, "card2");

        searchNameBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchNameBTN.setText("Search Name");

        searchPhoneBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchPhoneBTN.setText("Search Email");

        searchEmailBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchEmailBTN.setText("Search Phone");

        namePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        namePanel.setPreferredSize(new java.awt.Dimension(175, 25));

        searchCustomerLastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Name"));

        searchCustomerFirstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder("First Name"));

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerLastNameField)
                    .addComponent(searchCustomerFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(searchCustomerFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCustomerLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        phonePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        searchCustomerPhoneField.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone"));
        try {
            searchCustomerPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout phonePanelLayout = new javax.swing.GroupLayout(phonePanel);
        phonePanel.setLayout(phonePanelLayout);
        phonePanelLayout.setHorizontalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerPhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        phonePanelLayout.setVerticalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(searchCustomerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        emailPanel.setPreferredSize(new java.awt.Dimension(175, 22));

        searchCustomerEmailField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(searchCustomerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(searchNameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchEmailBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(searchPhoneBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(emailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(phonePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmailBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPhoneBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        mainPanel.add(searchCustomerPanel, "card3");

        NewCustomerPanel.setName(""); // NOI18N

        ncPhoneField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        try {
            ncPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ncFirstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncLastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        ncLastNameField.setMinimumSize(new java.awt.Dimension(15, 40));

        ncCityField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncBirthField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        ncBirthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));
        ncBirthField.setPreferredSize(new java.awt.Dimension(15, 40));

        ncStreetField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Street", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncEmailField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncCountryField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncStateField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ncTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ncTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ncTitleLabel.setText("New Customer Information");

        ncClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ncClearButton.setText("Clear");

        ncSubmitBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ncSubmitBTN.setText("Submit");

        javax.swing.GroupLayout NewCustomerPanelLayout = new javax.swing.GroupLayout(NewCustomerPanel);
        NewCustomerPanel.setLayout(NewCustomerPanelLayout);
        NewCustomerPanelLayout.setHorizontalGroup(
            NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                                .addComponent(ncFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ncLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(ncBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ncStreetField)
                                    .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                                        .addComponent(ncCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ncStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(ncCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewCustomerPanelLayout.createSequentialGroup()
                                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ncPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ncSubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ncClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ncEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(ncTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        NewCustomerPanelLayout.setVerticalGroup(
            NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCustomerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ncTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(ncStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(NewCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncSubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        mainPanel.add(NewCustomerPanel, "card4");

        mrNewReservationBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mrNewReservationBTN.setText("New Reservation");

        mrExistingReservationBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mrExistingReservationBTN.setText("Existing Reservation");

        javax.swing.GroupLayout mainReservationPanelLayout = new javax.swing.GroupLayout(mainReservationPanel);
        mainReservationPanel.setLayout(mainReservationPanelLayout);
        mainReservationPanelLayout.setHorizontalGroup(
            mainReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainReservationPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(mrNewReservationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(mrExistingReservationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        mainReservationPanelLayout.setVerticalGroup(
            mainReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainReservationPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(mainReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrExistingReservationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrNewReservationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        mainPanel.add(mainReservationPanel, "card5");

        nrCheckOutField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Out (yyyy-mm-dd)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        try {
            nrCheckOutField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nrCheckOutField.setPreferredSize(new java.awt.Dimension(15, 40));

        nrTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nrTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrTitleLabel.setText("New Reservation Information");

        ncClearButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ncClearButton2.setText("Clear");

        ncSubmitBTN2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ncSubmitBTN2.setText("Submit");

        nrRoomsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# of Rooms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        nrCheckInField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check In (yyyy-mm-dd)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        try {
            nrCheckInField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nrCheckInField.setPreferredSize(new java.awt.Dimension(15, 40));

        roomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Single", "Double", "King", "Suite" }));
        roomTypeComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        nrGuestField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# of Guests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout newReservationPanelLayout = new javax.swing.GroupLayout(newReservationPanel);
        newReservationPanel.setLayout(newReservationPanelLayout);
        newReservationPanelLayout.setHorizontalGroup(
            newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newReservationPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newReservationPanelLayout.createSequentialGroup()
                        .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(nrRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(nrGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newReservationPanelLayout.createSequentialGroup()
                        .addComponent(nrCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(nrCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(newReservationPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(ncSubmitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ncClearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(newReservationPanelLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(nrTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        newReservationPanelLayout.setVerticalGroup(
            newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newReservationPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nrTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrGuestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(newReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncClearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncSubmitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        mainPanel.add(newReservationPanel, "card6");

        ecSearchByNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Reservation Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        erNumberField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation #", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout ecSearchByNumberPanelLayout = new javax.swing.GroupLayout(ecSearchByNumberPanel);
        ecSearchByNumberPanel.setLayout(ecSearchByNumberPanelLayout);
        ecSearchByNumberPanelLayout.setHorizontalGroup(
            ecSearchByNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecSearchByNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(erNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        ecSearchByNumberPanelLayout.setVerticalGroup(
            ecSearchByNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecSearchByNumberPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(erNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        erTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        erTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erTitleLabel.setText("Existing Reservation Lookup");

        ecSearchByNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        erFirstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        erLastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        erLastNameField.setMinimumSize(new java.awt.Dimension(15, 40));

        erCheckInField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check In (yyyy-mm-dd)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        try {
            erCheckInField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        erCheckInField.setPreferredSize(new java.awt.Dimension(15, 40));

        javax.swing.GroupLayout ecSearchByNamePanelLayout = new javax.swing.GroupLayout(ecSearchByNamePanel);
        ecSearchByNamePanel.setLayout(ecSearchByNamePanelLayout);
        ecSearchByNamePanelLayout.setHorizontalGroup(
            ecSearchByNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecSearchByNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ecSearchByNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ecSearchByNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(erFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(erLastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(erCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ecSearchByNamePanelLayout.setVerticalGroup(
            ecSearchByNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecSearchByNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(erFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(erLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(erCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ecSearchNameBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ecSearchNameBTN.setText("Search Name");

        ecSearchNumberBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ecSearchNumberBTN.setText("Search Number");

        javax.swing.GroupLayout existingReservationPanelLayout = new javax.swing.GroupLayout(existingReservationPanel);
        existingReservationPanel.setLayout(existingReservationPanelLayout);
        existingReservationPanelLayout.setHorizontalGroup(
            existingReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingReservationPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(erTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(existingReservationPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ecSearchByNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(ecSearchByNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingReservationPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(ecSearchNumberBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ecSearchNameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        existingReservationPanelLayout.setVerticalGroup(
            existingReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingReservationPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(erTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(existingReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ecSearchByNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ecSearchByNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(existingReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecSearchNumberBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ecSearchNameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPanel.add(existingReservationPanel, "card7");

        customerDisplayPanel.setName(""); // NOI18N

        cdPhoneField.setEditable(false);
        cdPhoneField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        try {
            cdPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cdFirstNameField.setEditable(false);
        cdFirstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdLastNameField.setEditable(false);
        cdLastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        cdLastNameField.setMinimumSize(new java.awt.Dimension(15, 40));

        cdCityField.setEditable(false);
        cdCityField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdBirthField.setEditable(false);
        cdBirthField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        cdBirthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));
        cdBirthField.setPreferredSize(new java.awt.Dimension(15, 40));

        cdStreetField.setEditable(false);
        cdStreetField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Street", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdEmailField.setEditable(false);
        cdEmailField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdCountryField.setEditable(false);
        cdCountryField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdStateField.setEditable(false);
        cdStateField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cdTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cdTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdTitleLabel.setText("Customer Information");

        cdClearBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cdClearBTN.setText("Clear");
        cdClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdClearBTNActionPerformed(evt);
            }
        });

        cdSubmitBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cdSubmitBTN.setText("Submit");
        cdSubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdSubmitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerDisplayPanelLayout = new javax.swing.GroupLayout(customerDisplayPanel);
        customerDisplayPanel.setLayout(customerDisplayPanelLayout);
        customerDisplayPanelLayout.setHorizontalGroup(
            customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                                .addComponent(cdFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cdLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(cdBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cdStreetField)
                                    .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                                        .addComponent(cdCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cdStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(cdCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerDisplayPanelLayout.createSequentialGroup()
                                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdSubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(cdTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        customerDisplayPanelLayout.setVerticalGroup(
            customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDisplayPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cdTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(cdStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(customerDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdSubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        mainPanel.add(customerDisplayPanel, "card10");

        mrCheckOutField.setEditable(false);
        mrCheckOutField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Out", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrReservationNumberField.setEditable(false);
        mrReservationNumberField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mrReservationNumberField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        mrLNameField.setEditable(false);
        mrLNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrFNameField.setEditable(false);
        mrFNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrCheckInField.setEditable(false);
        mrCheckInField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrPhoneField.setEditable(false);
        mrPhoneField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrRoomTypeField.setEditable(false);
        mrRoomTypeField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of Room(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrRoomNumbersField.setEditable(false);
        mrRoomNumbersField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room(s) Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrGuestsField.setEditable(false);
        mrGuestsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# of Guests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        mrCostField.setEditable(false);
        mrCostField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mrCostField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        mrDeleteBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mrDeleteBTN.setText("Delete Reservation");
        mrDeleteBTN.setActionCommand("Delete Reservation");

        mrModifyBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mrModifyBTN.setText("Modify Reservation");

        javax.swing.GroupLayout modifyReservationPanelLayout = new javax.swing.GroupLayout(modifyReservationPanel);
        modifyReservationPanel.setLayout(modifyReservationPanelLayout);
        modifyReservationPanelLayout.setHorizontalGroup(
            modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyReservationPanelLayout.createSequentialGroup()
                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyReservationPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(mrReservationNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyReservationPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyReservationPanelLayout.createSequentialGroup()
                                .addComponent(mrFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mrLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(mrPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modifyReservationPanelLayout.createSequentialGroup()
                                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(modifyReservationPanelLayout.createSequentialGroup()
                                        .addComponent(mrCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mrCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrGuestsField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mrRoomTypeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(mrRoomNumbersField, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyReservationPanelLayout.createSequentialGroup()
                                .addComponent(mrModifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mrDeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        modifyReservationPanelLayout.setVerticalGroup(
            modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyReservationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mrReservationNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrGuestsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mrRoomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mrCostField)
                    .addComponent(mrRoomNumbersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(modifyReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrDeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrModifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        mainPanel.add(modifyReservationPanel, "card8");

        frCheckOutField.setEditable(false);
        frCheckOutField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Out", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frResNumField.setEditable(false);
        frResNumField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        frResNumField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        frLastNameField.setEditable(false);
        frLastNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frFirstNameField.setEditable(false);
        frFirstNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frCheckInField.setEditable(false);
        frCheckInField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frPhoneField.setEditable(false);
        frPhoneField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frRoomTypeField.setEditable(false);
        frRoomTypeField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of Room(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frRoomNumbersField.setEditable(false);
        frRoomNumbersField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room(s) Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frGuestsField.setEditable(false);
        frGuestsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "# of Guests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        frCostField.setEditable(false);
        frCostField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frCostField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        frCancelBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        frCancelBTN.setText("Cancel Reservation");

        frFinalizeBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        frFinalizeBTN.setText("Finalize Reservation");

        javax.swing.GroupLayout finalizeReservationPanelLayout = new javax.swing.GroupLayout(finalizeReservationPanel);
        finalizeReservationPanel.setLayout(finalizeReservationPanelLayout);
        finalizeReservationPanelLayout.setHorizontalGroup(
            finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalizeReservationPanelLayout.createSequentialGroup()
                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, finalizeReservationPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(frResNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, finalizeReservationPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(finalizeReservationPanelLayout.createSequentialGroup()
                                .addComponent(frFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(frLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(frPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(finalizeReservationPanelLayout.createSequentialGroup()
                                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(finalizeReservationPanelLayout.createSequentialGroup()
                                        .addComponent(frCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(frCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frGuestsField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(frRoomTypeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(frRoomNumbersField, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalizeReservationPanelLayout.createSequentialGroup()
                                .addComponent(frFinalizeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(frCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        finalizeReservationPanelLayout.setVerticalGroup(
            finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalizeReservationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(frResNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frGuestsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(frRoomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frCostField)
                    .addComponent(frRoomNumbersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(finalizeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frFinalizeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        mainPanel.add(finalizeReservationPanel, "card9");

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        returnCustomerBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnCustomerBTN.setText("Return to Customer Screen");
        returnCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCustomerBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(returnCustomerBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnCustomerBTN)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void returnCustomerBTNActionPerformed(ActionEvent evt) {//GEN-FIRST:event_returnCustomerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnCustomerBTNActionPerformed

    private void validateCredentialsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateCredentialsBTNActionPerformed
                    //As long 
    }//GEN-LAST:event_validateCredentialsBTNActionPerformed

    private void newCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCustomerBTNActionPerformed

    private void existingCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingCustomerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existingCustomerBTNActionPerformed

    private void cdSubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdSubmitBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdSubmitBTNActionPerformed

    private void cdClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdClearBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdClearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewCustomerPanel;
    private javax.swing.JFormattedTextField cdBirthField;
    private javax.swing.JTextField cdCityField;
    private javax.swing.JButton cdClearBTN;
    private javax.swing.JTextField cdCountryField;
    private javax.swing.JTextField cdEmailField;
    private javax.swing.JTextField cdFirstNameField;
    private javax.swing.JTextField cdLastNameField;
    private javax.swing.JFormattedTextField cdPhoneField;
    private javax.swing.JTextField cdStateField;
    private javax.swing.JTextField cdStreetField;
    private javax.swing.JButton cdSubmitBTN;
    private javax.swing.JLabel cdTitleLabel;
    private javax.swing.JPanel customerDisplayPanel;
    private javax.swing.JPanel ecSearchByNamePanel;
    private javax.swing.JPanel ecSearchByNumberPanel;
    private javax.swing.JButton ecSearchNameBTN;
    private javax.swing.JButton ecSearchNumberBTN;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField employeeIDField;
    private javax.swing.JFormattedTextField erCheckInField;
    private javax.swing.JTextField erFirstNameField;
    private javax.swing.JTextField erLastNameField;
    private javax.swing.JTextField erNumberField;
    private javax.swing.JLabel erTitleLabel;
    private javax.swing.JButton existingCustomerBTN;
    private javax.swing.JPanel existingReservationPanel;
    private javax.swing.JPanel finalizeReservationPanel;
    private javax.swing.JButton frCancelBTN;
    private javax.swing.JTextField frCheckInField;
    private javax.swing.JTextField frCheckOutField;
    private javax.swing.JTextField frCostField;
    private javax.swing.JButton frFinalizeBTN;
    private javax.swing.JTextField frFirstNameField;
    private javax.swing.JTextField frGuestsField;
    private javax.swing.JTextField frLastNameField;
    private javax.swing.JTextField frPhoneField;
    private javax.swing.JTextField frResNumField;
    private javax.swing.JTextField frRoomNumbersField;
    private javax.swing.JTextField frRoomTypeField;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainCustomerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainReservationPanel;
    private javax.swing.JPanel modifyReservationPanel;
    private javax.swing.JTextField mrCheckInField;
    private javax.swing.JTextField mrCheckOutField;
    private javax.swing.JTextField mrCostField;
    private javax.swing.JButton mrDeleteBTN;
    private javax.swing.JButton mrExistingReservationBTN;
    private javax.swing.JTextField mrFNameField;
    private javax.swing.JTextField mrGuestsField;
    private javax.swing.JTextField mrLNameField;
    private javax.swing.JButton mrModifyBTN;
    private javax.swing.JButton mrNewReservationBTN;
    private javax.swing.JTextField mrPhoneField;
    private javax.swing.JTextField mrReservationNumberField;
    private javax.swing.JTextField mrRoomNumbersField;
    private javax.swing.JTextField mrRoomTypeField;
    private javax.swing.JPanel namePanel;
    private javax.swing.JFormattedTextField ncBirthField;
    private javax.swing.JTextField ncCityField;
    private javax.swing.JButton ncClearButton;
    private javax.swing.JButton ncClearButton2;
    private javax.swing.JTextField ncCountryField;
    private javax.swing.JTextField ncEmailField;
    private javax.swing.JTextField ncFirstNameField;
    private javax.swing.JTextField ncLastNameField;
    private javax.swing.JFormattedTextField ncPhoneField;
    private javax.swing.JTextField ncStateField;
    private javax.swing.JTextField ncStreetField;
    private javax.swing.JButton ncSubmitBTN;
    private javax.swing.JButton ncSubmitBTN2;
    private javax.swing.JLabel ncTitleLabel;
    private javax.swing.JButton newCustomerBTN;
    private javax.swing.JPanel newReservationPanel;
    private javax.swing.JFormattedTextField nrCheckInField;
    private javax.swing.JFormattedTextField nrCheckOutField;
    private javax.swing.JTextField nrGuestField;
    private javax.swing.JTextField nrRoomsField;
    private javax.swing.JLabel nrTitleLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JButton returnCustomerBTN;
    private javax.swing.JComboBox<String> roomTypeComboBox;
    private javax.swing.JTextField searchCustomerEmailField;
    private javax.swing.JTextField searchCustomerFirstNameField;
    private javax.swing.JTextField searchCustomerLastNameField;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JFormattedTextField searchCustomerPhoneField;
    private javax.swing.JButton searchEmailBTN;
    private javax.swing.JButton searchNameBTN;
    private javax.swing.JButton searchPhoneBTN;
    private javax.swing.JButton validateCredentialsBTN;
    // End of variables declaration//GEN-END:variables
}
